use_frameworks!

platform :ios, '8.0'

target 'KoalaCoreSDK_Example' do
  pod 'KoalaCoreSDK', :path => '../'

  target 'KoalaCoreSDK_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
